name: Continuous Integration

on:
  pull_request:
    branches: ['1.x']
  push:
    branches: ['1.x']

jobs:
  phpunit:
    name: PHPUnit (PHP ${{ matrix.php-version }})
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        php-version:
          - '8.1'
          - '8.2'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install PHP with pcov
        uses: shivammathur/setup-php@v2
        with:
          coverage: pcov
          php-version: ${{ matrix.php-version }}

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v2

      - name: Run PHPUnit
        run: vendor/bin/phpunit --coverage-clover=coverage.xml

      - name: Upload to Codecov
        uses: codecov/codecov-action@v3
        if: matrix.php-version == '8.1'
